# Generated by Django 4.0.2 on 2022-03-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buystock',
            name='ref_code',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
