# Generated by Django 4.0.2 on 2022-03-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_buystock_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='buystock',
            name='average_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
