# Generated by Django 4.0.2 on 2022-03-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_buystock_average_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total_share',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
