# Generated by Django 4.0.2 on 2022-03-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_buystock_total_average_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='buystock',
            name='total_investment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
