# Generated by Django 4.0.2 on 2022-03-12 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_buystock_total_investment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('commission_fee', models.FloatField(default=0.0025)),
                ('vat', models.FloatField(default=0.12)),
                ('trans_fee', models.FloatField(default=5e-05)),
                ('sccp_fee', models.FloatField(default=0.0001)),
                ('sales_tax', models.FloatField(default=0.006)),
            ],
        ),
        migrations.AddField(
            model_name='buystock',
            name='broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stocks.broker'),
        ),
    ]
