# Generated by Django 4.0.2 on 2022-03-13 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_broker_buystock_broker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buystock',
            name='broker',
        ),
        migrations.AddField(
            model_name='stock',
            name='broker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stocks.broker'),
        ),
    ]
